### ISSUE TITLE
zrpc redis鉴权不生效

### ISSUE THREAD

**Issue by zjz894251se** [tal-tech/go-zero#211]
调试发现auth.Authenticate 这个方法没有走，是哪里设置错了吗？
```yaml
Auth: true
StrictControl: false
Redis:
  Key: appserver.auth
  Host: 127.0.0.1:6379
  Type: node
```
