### ISSUE TITLE
goctl docker generate的用法

### ISSUE THREAD

**Issue by scfobao** [tal-tech/go-zero#217]
请教一下大佬，bookstore中，我需要生成哪些dockerfile,怎么生成？然后怎么用？
如果需要在k8s中部署，有没有可以参考的配置文件？
谢谢

**Comment by kevwan** [comment]
有main函数的就需要生成 `Dockerfile`，`goctl docker` 命令可以生成

**Comment by scfobao** [comment]
在哪一级目录执行这个命令

**Comment by kevwan** [comment]
> 在哪一级目录执行这个命令

main函数所在的目录

**Comment by scfobao** [comment]
` ---> 4978bfdeee6e
Step 9/18 : RUN go build -ldflags="-s -w" -o /app/bookstore bookstore.go
 ---> Running in 66a14b954fce
bookstore.go:7:2: cannot find package "bookstore/api/internal/config" in any of:
        /usr/local/go/src/bookstore/api/internal/config (from $GOROOT)
        /go/src/bookstore/api/internal/config (from $GOPATH)
bookstore.go:8:2: cannot find package "bookstore/api/internal/handler" in any of:
        /usr/local/go/src/bookstore/api/internal/handler (from $GOROOT)
        /go/src/bookstore/api/internal/handler (from $GOPATH)
bookstore.go:9:2: cannot find package "bookstore/api/internal/svc" in any of:
        /usr/local/go/src/bookstore/api/internal/svc (from $GOROOT)
        /go/src/bookstore/api/internal/svc (from $GOPATH)
bookstore.go:11:2: cannot find package "github.com/tal-tech/go-zero/core/conf" in any of:
        /usr/local/go/src/github.com/tal-tech/go-zero/core/conf (from $GOROOT)
        /go/src/github.com/tal-tech/go-zero/core/conf (from $GOPATH)
bookstore.go:12:2: cannot find package "github.com/tal-tech/go-zero/rest" in any of:
        /usr/local/go/src/github.com/tal-tech/go-zero/rest (from $GOROOT)
        /go/src/github.com/tal-tech/go-zero/rest (from $GOPATH)
The command '/bin/sh -c go build -ldflags="-s -w" -o /app/bookstore bookstore.go' returned a non-zero code: 1`

**Comment by scfobao** [comment]
可以了。多谢

**Comment by scfobao** [comment]
做了一个docker-compose.yml
```
version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - add
      - check
    ports:
      - "8888:8888"
  add:
    build:
      context: .
      dockerfile: ./rpc/add/Dockerfile
    ports:
      - "8080:8080"
  check:
    build:
      context: .
      dockerfile: ./rpc/check/Dockerfile
    ports:
      - "8081:8081"      
```
