### ISSUE TITLE
希望加个zrpc 直连 的范例

### ISSUE THREAD

**Issue by 15951836388** [tal-tech/go-zero#366]
rt

**Comment by Code-Fight** [comment]
### 很简单，就那shorturl那个例子来说，你只需要做一件事，就可以完成

1. 首先，打开这个例子，查看第 7 步，链接如下
[修改 API Gateway 代码调用 transform rpc 服务](https://github.com/tal-tech/zero-doc/blob/main/doc/shorturl.md#7-%E4%BF%AE%E6%94%B9-api-gateway-%E4%BB%A3%E7%A0%81%E8%B0%83%E7%94%A8-transform-rpc-%E6%9C%8D%E5%8A%A1)

2. 然后修改把配置文件改为如下即可

```
Transform:
  Endpoints: 
    Hosts:
      - localhost:2379
```

 **就是把配置的etcd换成Endpoints ，去掉etcd的key就可以了**
