### ISSUE TITLE
启动服务出现error: type mismatch for field Pass

### ISSUE THREAD

**Issue by wendy-rose** [tal-tech/go-zero#901]
使用CacheRedis，yaml文件如下配置
```yaml
Name: user-api
Host: 0.0.0.0
Port: 8888
Mysql:
  DataSource: root:root@tcp(127.0.0.1:3306)/go-test?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: 127.0.0.1:6379
    Pass: 123456
    Type: node
Auth:
  AccessSecret: CD3E38AC631E8369A3B1300C24D27F11
  AccessExpire: 7200
```
启动命令
`go run user.go -f etc/user-api.yaml`

启动后出现
2021/08/11 15:50:05 error: config file etc/user-api.yaml, error: type mismatch for field Pass
exit status 1

我看了文档也是这样配置，不知道为什么这里不可以
